### ISSUE TITLE
Run migrations on empty database fails with "Package "friendsofphp/proxy-manager-lts" is not installed"

### ISSUE THREAD

**Issue by tezhm** [doctrine/migrations#1112]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.3.2

#### Summary

When running migrations on empty database, the command fails with due to missing a package "friendsofphp/proxy-manager-lts".

#### Previous behavior

Would build the migrations table in database and run all relevant migrations.

#### Current behavior

Outputs the following error:

```
Package "friendsofphp/proxy-manager-lts" is not installed {"exception":"[object] (OutOfBoundsException(code: 0): Package \"friendsofphp/proxy-manager-lts\" is not installed at /.../vendor/composer/composer/src/Composer/InstalledVersions.php:127)

[stacktrace]
#0 /.../vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/Version.php(41): Composer\\InstalledVersions::getPrettyVersion()
#1 /.../vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/Factory/AbstractBaseFactory.php(73): ProxyManager\\Version::getVersion()
#2 /.../vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php(53): ProxyManager\\Factory\\AbstractBaseFactory->generateProxy()
#3 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Provider/LazySchemaDiffProvider.php(57): ProxyManager\\Factory\\LazyLoadingValueHolderFactory->createProxy()
#4 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/Executor.php(398): Doctrine\\Migrations\\Provider\\LazySchemaDiffProvider->createFromSchema()
#5 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/Executor.php(197): Doctrine\\Migrations\\Version\\Executor->getFromSchema()
#6 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/Executor.php(129): Doctrine\\Migrations\\Version\\Executor->executeMigration()
#7 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/Version.php(185): Doctrine\\Migrations\\Version\\Executor->execute()
#8 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Migrator.php(182): Doctrine\\Migrations\\Version\\Version->execute()
#9 /.../vendor/doctrine/migrations/lib/Doctrine/Migrations/Migrator.php(148): Doctrine\\Migrations\\Migrator->executeMigration()
#10 /.../vendor/laravel-doctrine/migrations/src/Migrator.php(28): Doctrine\\Migrations\\Migrator->migrate()
#11 /.../vendor/laravel-doctrine/migrations/src/Console/MigrateCommand.php(77): LaravelDoctrine\\Migrations\\Migrator->migrate()
#12 /.../vendor/illuminate/container/BoundMethod.php(36): LaravelDoctrine\\Migrations\\Console\\MigrateCommand->handle()
#13 /.../vendor/illuminate/container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /.../vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /.../vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /.../vendor/illuminate/container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#17 /.../vendor/illuminate/console/Command.php(134): Illuminate\\Container\\Container->call()
#18 /.../vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#19 /.../vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#20 /.../vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#21 /.../vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /.../vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#23 /.../vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#24 /.../vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run()
#25 /.../artisan(35): Laravel\\Lumen\\Console\\Kernel->handle()
#26 {main}
```

#### How to reproduce

(Using laravel doctrine) `php artisan doctrine:migrations:migrate`

**Comment by greg0ire** [comment]
@nicolas-grekas , can you please look into this?

**Comment by nicolas-grekas** [comment]
The package is obviously installed. Did you run Composer with the `--no-scripts` or `--no-plugins` argument?
Can you provide a reproducer?

**Comment by tezhm** [comment]
Yes, doesn't seem to be a problem with how it's installed. Seems that it depends on composer runtime api which there's no dependency for.

![image](https://user-images.githubusercontent.com/6971400/104545760-83112280-5676-11eb-9056-95bdc65fca59.png)

![image](https://user-images.githubusercontent.com/6971400/104545796-90c6a800-5676-11eb-8e9c-ae200f38c61e.png)

**Comment by greg0ire** [comment]
I think you are reading that backwards. If you use `composer-runtime-api ^2.0`, you will get that file, not the other way around. Which version of Composer are you using?

>  Did you run Composer with the `--no-scripts` or `--no-plugins` argument?

>> Yes

Well there's your problem, you shouldn't.

**Comment by tezhm** [comment]
Oh sorry I thought you wanted me to test with no plugins and no scripts. Either way I get the same issue. 

I'm still on composer v1, can't give exact version until tomorrow. 

I've got a composer project so that explains why the file is there, I don't have the composer runtime api dependency anywhere. 

The friends of php ProxyManager/Version class has a hard dependency on that file. From debugging, found that static `$installed` property was empty.

I'm guessing something needs to register against that list and it isn't. Is there a missing dependency not included by doctrine/migrations I'm meant to add? Or a service provider that needs to be registered against my lumen application?

**Comment by Brewal** [comment]
I have the exact same problem. I run `composer install` with no flags

`Composer version 1.10.17 2020-10-30 22:31:58`

```
doctrine/migrations 2.3.2 PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. It is a very easy to use and a powerful tool.
├──composer/package-versions-deprecated ^1.8
│  ├──composer-plugin-api ^1.1.0 || ^2.0
│  └──php ^7 || ^8
├──doctrine/dbal ^2.9
│  ├──doctrine/cache ^1.0
│  │  └──php ~7.1 || ^8.0
│  ├──doctrine/event-manager ^1.0
│  │  └──php ^7.1 || ^8.0
│  ├──ext-pdo *
│  └──php ^7.3 || ^8
├──friendsofphp/proxy-manager-lts ^1.0
│  ├──laminas/laminas-code ~3.4.1|^4.0
│  │  ├──laminas/laminas-eventmanager ^3.3
│  │  │  ├──laminas/laminas-zendframework-bridge ^1.0
│  │  │  │  └──php ^5.6 || ^7.0 || ^8.0
│  │  │  └──php ^7.3 || ^8.0
│  │  └──php ^7.4 || ~8.0.0
│  ├──php >=7.1
│  └──symfony/filesystem ^4.4.17|^5.0
│     ├──php >=7.1.3
│     └──symfony/polyfill-ctype ~1.8
├──php ^7.1 || ^8.0
├──symfony/console ^3.4||^4.4.16||^5.0
│  ├──php >=7.1.3
│  ├──symfony/polyfill-mbstring ~1.0
│  │  └──php >=7.1
│  ├──symfony/polyfill-php73 ^1.8
│  │  └──php >=7.1
│  ├──symfony/polyfill-php80 ^1.15
│  │  └──php >=7.1
│  └──symfony/service-contracts ^1.1|^2
│     ├──php >=7.2.5
│     └──psr/container ^1.0
│        └──php >=5.3.0
└──symfony/stopwatch ^3.4||^4.0||^5.0
   ├──php >=7.1.3
   └──symfony/service-contracts ^1.0|^2
      ├──php >=7.2.5
      └──psr/container ^1.0
         └──php >=5.3.0
```

Running `php bin/console doctrine:migrations:migrate` also fails with Symfony.

After trying an update to version `3.0.2`, it also fails.

`composer info | grep doctrine` : 

```
beberlei/doctrineextensions                    v1.3.0            
doctrine/annotations                           1.11.1            
doctrine/cache                                 1.10.2            
doctrine/collections                           1.6.7             
doctrine/common                                2.13.3            
doctrine/data-fixtures                         1.4.4             
doctrine/dbal                                  2.12.1            
doctrine/doctrine-bundle                       2.2.2             
doctrine/doctrine-migrations-bundle            3.0.2             
doctrine/event-manager                         1.1.1             
doctrine/inflector                             1.4.3             
doctrine/instantiator                          1.4.0             
doctrine/lexer                                 1.2.1             
doctrine/migrations                            3.0.2             
doctrine/orm                                   2.7.5             
doctrine/persistence                           1.3.8             
doctrine/reflection                            1.2.2             
doctrine/sql-formatter                         1.1.1             
gedmo/doctrine-extensions                      v3.0.0            
ramsey/uuid-doctrine                           1.6.0             
stof/doctrine-extensions-bundle                v1.5.0            
symfony/doctrine-bridge                        v4.4.18 
```

With composer v2, I don't have the problem.

**Comment by greg0ire** [comment]
Can one of you work on providing a reproducer (either a repository or script that reproduces the issue)?

**Comment by nicolas-grekas** [comment]
Should be fixed by https://github.com/FriendsOfPHP/proxy-manager-lts/pull/5

**Comment by greg0ire** [comment]
Thanks @nicolas-grekas !
