### ISSUE TITLE
Doctrine Migrations cannot launch any command

### ISSUE THREAD

**Issue by dardinier** [doctrine/migrations#559]
# Situation
- I use `Doctrine Migrations v1.5.0`

- I defined a file as :
`/usr/local/bin/doctrine-migrations`:
```
#!/bin/sh
php /home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar "$@"
```

- I have a folder :
```
.
├── migrations-db.php
├── migrations.yml
└── src
    └── DoctrineMigrations
```

- `migrations-db.php` :
```
<?php
return array(
    'url' => 'mysqli://root:toor@localhost/testDB'
);
?>
```
- `migrations.yml` :
```
name: Doctrine Sandbox Migrations
migrations_namespace: DoctrineMigrations
table_name: doctrine_migration_versions
migrations_directory: /src/DoctrineMigrations
```
# Context
I can generate a version with `doctrine-migrations migrations:generate`.

Result :
```
Loading configuration from file: migrations.yml
Generated new migration class to "/home/adardinier/workspace/doctrine-migrations/src/DoctrineMigrations/Version20171024150037.php"
```
My Version is generated correctly :
```
.
├── migrations-db.php
├── migrations.yml
└── src
    └── DoctrineMigrations
        └── Version20171024150037.php
```
`Version20171024150037.php` :
```
<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20171024150037 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
```
# Problem

If I generate a second version, with the exact same way : `doctrine-migrations migrations:generate`,
I get this error :
```
Loading configuration from file: migrations.yml
PHP Fatal error:  Uncaught Error: Call to undefined function Doctrine\DBAL\Driver\Mysqli\mysqli_init() in phar:///home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php:64
Stack trace:
#0 phar:///home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(36): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->__construct(Array, 'root', 'toor', Array)
#1 phar:///home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'root', 'toor', Array)
#2 phar:///home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#3 phar:///home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBA in phar:///home/adardinier/Tools/doctrine-migrations/doctrine-migrations.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php on line 64
```

So the first call generate the version but a second one produce an error ...

Same error with `doctrine-migrations migrations:status`, `doctrine-migrations migrations:migrate`, etc ...

**Comment by lcobucci** [comment]
@dardinier `Call to undefined function Doctrine\DBAL\Driver\Mysqli\mysqli_init()` means that you probably don't have `ext-mysqli` installed and DBAL is failing to open a connection.
One strange thing is that, as far as I saw (in `master`), `migrations:generate` doesn't require the DB connection so you should be able to run the command many times. 

Please make sure you have that extension installed and enabled or change the configuration to use something else (PDO, maybe).

**Comment by dardinier** [comment]
Tanks @lcobucci,
I wasn't in my container so my environment wasn't configured as required.
Since I work in my container, everything work correctly.
