### ISSUE TITLE
latest phar does not work complaining about unexisting getVariadic method

### ISSUE THREAD

**Issue by Gamesh** [doctrine/migrations#922]
### Bug Report

```
Migration 20200125193137 failed during Pre-Checks. Error Call to undefined method Zend\Code\Generator\ParameterGenerator::getVariadic()
PHP Fatal error:  Uncaught Error: Call to undefined method Zend\Code\Generator\ParameterGenerator::getVariadic() in phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php:91
Stack trace:
#0 [internal function]: ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\Constructor::ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\{closure}(Object(Zend\Code\Generator\ParameterGenerator))
#1 phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php(93): array_map(Object(Closure), Array)
#2 phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php(67): ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\Constructor::generateOriginalConstructorCall(Object(ReflectionClass), Object(ProxyManager\ProxyGenerator\LazyLoadingValueHolder\PropertyGener in phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php on line 91

Fatal error: Uncaught Error: Call to undefined method Zend\Code\Generator\ParameterGenerator::getVariadic() in phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php:91
Stack trace:
#0 [internal function]: ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\Constructor::ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\{closure}(Object(Zend\Code\Generator\ParameterGenerator))
#1 phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php(93): array_map(Object(Closure), Array)
#2 phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php(67): ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\Constructor::generateOriginalConstructorCall(Object(ReflectionClass), Object(ProxyManager\ProxyGenerator\LazyLoadingValueHolder\PropertyGener in phar:///var/www/html/doctrine-migrations.phar/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/ValueHolder/MethodGenerator/Constructor.php on line 91
```

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.2.1
| PHP | v7.2

#### Summary

running migration:migrate fails with error: `Error Call to undefined method Zend\Code\Generator\ParameterGenerator::getVariadic()`

**Comment by skybluesofa** [comment]
I get this same error message when using a `cli-config.php` file. If I just use the `migrations.php` and `migrations-db.php` as directed in the instructions, the migrations work fine.

**Comment by SenseException** [comment]
@skybluesofa Do you see an issue with the documentation? Is it unclear or are there undocumented details to make it more understandable?
